USE SUELDOS
CREATE TABLE CATEGORIAS(
	Cod_Categoria char(2) NOT NULL,
	Desc_Categoria varchar(50) NOT NULL,
	CONSTRAINT PK_CATEGORIAS PRIMARY KEY CLUSTERED
	(
		Cod_Categoria
	)ON [PRIMARY]
) ON [PRIMARY]