--Agregar campo
USE SUELDOS
ALTER TABLE CATEGORIAS
ADD Usuario Varchar(30)
--Eliminar campo
USE SUELDOS
ALTER TABLE CATEGORIAS
DROP COLUMN Usuario
--Eliminar tabla
USE SUELDOS
DROP TABLE CATEGORIAS
--Insertar datos
USE SUELDOS
INSERT INTO CATEGORIAS(Cod_Categoria,Desc_Categoria)
VALUES('CA','CADETE'),('PL','POLICIA')
--Usar SELECT
USE SUELDOS
SELECT * FROM CATEGORIAS
--usar SELECT FILTRADO
USE SUELDOS
SELECT * FROM CATEGORIAS
WHERE Cod_Categoria = 'CA'
--usar UPDATE
USE SUELDOS
UPDATE CATEGORIAS
SET Desc_Categoria = 'Capataz'
WHERE Cod_Categoria = 'CA'
---ELIMINAR REGISTROS
--ELIMINA TODOS LOS REGISTROS
USE SUELDOS
DELETE FROM CATEGORIAS
--
USE SUELDOS
DELETE CATEGORIAS
--ELIMINA REGISTROS ESPECIFICOS
USE SUELDOS
DELETE FROM CATEGORIAS
WHERE Cod_Categoria = 'CA'